
[functions.auto-close-engine]
enabled = true
verify_jwt = true
import_map = "./functions/auto-close-engine/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/auto-close-engine/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/auto-close-engine/*.html" ]

[functions.market-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/market-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/market-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/market-proxy/*.html" ]
